# Generated by Django 2.0.5 on 2018-05-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_history', models.BooleanField(default=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_phone', models.CharField(blank=True, max_length=12)),
                ('event_date', models.DateField(verbose_name='event date')),
                ('pickup_date', models.DateField(blank=True, verbose_name='pickup date')),
                ('assoc_name', models.CharField(max_length=30)),
                ('entry_date', models.DateField(verbose_name='date published')),
                ('total_amt', models.IntegerField(blank=True, default=0, verbose_name='total drinks purchased')),
                ('total_cost', models.IntegerField(blank=True, default=0, verbose_name='total $$ spent')),
                ('return_amt', models.IntegerField(blank=True, default=0, verbose_name='total $$ returned')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=40)),
                ('product_size', models.IntegerField(blank=True, verbose_name='size of item in mL/6-pack/case')),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('product_qty', models.IntegerField(blank=True, verbose_name='Number of items purchased')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.Event')),
            ],
        ),
    ]
